---

# maubot is a plugin-based Matrix bot system.
# Project source code URL: https://mau.dev/maubot/maubot

matrix_bot_maubot_enabled: true
matrix_bot_maubot_container_image_self_build: false
matrix_bot_maubot_docker_repo: "https://mau.dev/maubot/maubot.git"
matrix_bot_maubot_container_image_self_build_repo: "https://mau.dev/maubot/maubot.git"

# matrix_bot_maubot_container_image_customizations_enabled controls whether a customized Maubot image will be built.
#
# We toggle this variable to `true` when certain features which require a custom build are enabled.
# Feel free to toggle this to `true` yourself and specify build steps in `matrix_bot_maubot_container_image_customizations_dockerfile_body_custom`.
#
# See:
# - `roles/custom/matrix-bot-maubot/templates/customizations/Dockerfile.j2`
# - `matrix_bot_maubot_container_image_customizations_dockerfile_body_custom`
# - `matrix_bot_maubot_docker_image_customized`
# - `matrix_bot_maubot_docker_image_final`

matrix_bot_maubot_container_image_customizations_enabled: |-
  {{
    matrix_bot_maubot_container_image_customizations_azure_dependencies_installation_enabled
    or
    matrix_bot_maubot_container_image_customizations_encryption_enabled
    or
    matrix_bot_maubot_container_image_customizations_templates_enabled
  }}

# Controls whether custom build steps will be added to the Dockerfile for installing Azure dependencies.
# The version that will be installed is specified in `matrix_bot_maubot_azure_dependencies_version`.
matrix_bot_maubot_container_image_customizations_azure_dependencies_installation_enabled: "{{ matrix_bot_maubot_azure_dependencies_installation_enabled }}"

# Controls whether custom build steps will be added to the Dockerfile for customizing the email templates used by Maubot.
#
# Example usage:
#
# ```yml
# matrix_bot_maubot_container_image_customizations_templates_enabled: true
# # The templates are expected to be in a `templates/` subdirectory in
# matrix_bot_maubot_container_image_customizations_templates_in_container_template_files_relative_path: templates/
# matrix_bot_maubot_container_image_customizations_templates_git_repository_url: git@github.com:organization/repository.git
# matrix_bot_maubot_container_image_customizations_templates_git_repository_branch: main
# matrix_bot_maubot_container_image_customizations_templates_git_repository_keyscan_enabled: true
# matrix_bot_maubot_container_image_customizations_templates_git_repository_keyscan_hostname: github.com
# ```
#
# See: https://github.com/matrix-org/synapse/blob/develop/docs/templates.md
matrix_bot_maubot_container_image_customizations_templates_enabled: false
matrix_bot_maubot_container_image_customizations_templates_in_container_base_path: /custom-templates
matrix_bot_maubot_container_image_customizations_templates_in_container_template_files_relative_path: ''
matrix_bot_maubot_container_image_customizations_templates_in_container_full_path: "{{ matrix_bot_maubot_container_image_customizations_templates_in_container_base_path }}/{{ matrix_bot_maubot_container_image_customizations_templates_in_container_template_files_relative_path }}"
matrix_bot_maubot_container_image_customizations_templates_git_repository_url: ''
matrix_bot_maubot_container_image_customizations_templates_git_repository_branch: main
matrix_bot_maubot_container_image_customizations_templates_git_repository_keyscan_enabled: false
matrix_bot_maubot_container_image_customizations_templates_git_repository_keyscan_hostname: ''

# matrix_bot_maubot_container_image_customizations_dockerfile_body contains your custom Dockerfile steps
# for building your customized Maubot image based on the original (upstream) image (`matrix_bot_maubot_docker_image`).
# A `FROM ...` clause is included automatically so you don't have to.
#
# Example:
# matrix_bot_maubot_container_image_customizations_dockerfile_body_custom: |
#  RUN echo 'This is a custom step for building the customized Docker image for Maubot.'
#  RUN echo 'You can override matrix_bot_maubot_container_image_customizations_dockerfile_body_custom to add your own steps.'
#  RUN echo 'You do NOT need to include a FROM clause yourself.'
matrix_bot_maubot_container_image_customizations_dockerfile_body_custom: ''

# matrix_bot_maubot_docker_image_customized is the name of the locally built Maubot image
# which adds various customizations on top of the original (upstream) Maubot image.
# This image will be based on the upstream `matrix_bot_maubot_docker_image` image, only if `matrix_bot_maubot_container_image_customizations_enabled: true`.
matrix_bot_maubot_docker_image_customized: "localhost/matrixdotorg/bot_maubot:{{ matrix_bot_maubot_docker_image_tag }}-customized"

# Controls whether the customized image (`matrix_bot_maubot_docker_image_customized`) is to be force-built without layer caching enabled.
# This is useful if you've enabled customizations (e.g. `matrix_bot_maubot_container_image_customizations_templates_enabled`),
# which clone some branch of some repository, and you'd like for each Ansible run to pull new revisions from that branch.
matrix_bot_maubot_docker_image_customized_build_nocache: true

# Controls whether the customized image (`matrix_bot_maubot_docker_image_customized`) is to be built, even if it already exists.
# Related to: matrix_bot_maubot_docker_image_customized_build_nocache
matrix_bot_maubot_docker_image_customized_force_source: "{{ matrix_bot_maubot_docker_image_customized_build_nocache }}"

# matrix_bot_maubot_docker_image_final holds the name of the Maubot image to run depending on whether or not customizations are enabled.
matrix_bot_maubot_docker_image_final: "{{ matrix_bot_maubot_docker_image_customized if matrix_bot_maubot_container_image_customizations_enabled else matrix_bot_maubot_docker_image }} "

matrix_bot_maubot_docker_src_files_path: "{{ matrix_bot_maubot_base_path }}/docker-src"
matrix_bot_maubot_docker_repo_version: "{{ 'master' if matrix_bot_maubot_version == 'latest' else matrix_bot_maubot_version }}"

matrix_bot_maubot_customized_docker_src_files_path: "{{ matrix_bot_maubot_base_path }}/docker-src"

matrix_bot_maubot_version: v0.4.1
matrix_bot_maubot_docker_image: "{{ matrix_bot_maubot_docker_image_name_prefix }}maubot/maubot:{{ matrix_bot_maubot_version }}"
matrix_bot_maubot_docker_image_name_prefix: "{{ 'localhost/' if matrix_bot_maubot_container_image_self_build else 'dock.mau.dev/' }}"
matrix_bot_maubot_docker_image_force_pull: "{{ matrix_bot_maubot_docker_image.endswith(':latest') }}"

matrix_bot_maubot_base_path: "{{ matrix_base_data_path }}/maubot"
matrix_bot_maubot_data_path: "{{ matrix_bot_maubot_base_path }}/data"
matrix_bot_maubot_config_path: "{{ matrix_bot_maubot_base_path }}/config"

matrix_bot_maubot_bot_server_public_url: "https://{{ matrix_server_fqn_matrix }}"
matrix_bot_maubot_proxy_management_interface: true

matrix_bot_maubot_database_engine: sqlite
matrix_bot_maubot_sqlite_database_path_local: "{{ matrix_bot_maubot_data_path }}/maubot.db"
matrix_bot_maubot_sqlite_database_path_in_container: "/data/maubot.db"

matrix_bot_maubot_database_username: matrix_bot_maubot
matrix_bot_maubot_database_password: ~
matrix_bot_maubot_database_hostname: ''
matrix_bot_maubot_database_port: 5432
matrix_bot_maubot_database_name: matrix_bot_maubot
matrix_bot_maubot_database_sslmode: disable

matrix_bot_maubot_database_connection_string: postgres://{{ matrix_bot_maubot_database_username }}:{{ matrix_bot_maubot_database_password }}@{{ matrix_bot_maubot_database_hostname }}:{{ matrix_bot_maubot_database_port }}/{{ matrix_bot_maubot_database_name }}?sslmode={{ matrix_bot_maubot_database_sslmode }}

matrix_bot_maubot_database_uri: "{{
 	{
 		'sqlite': ('sqlite:///' + matrix_bot_maubot_sqlite_database_path_in_container),
 		'postgres': matrix_bot_maubot_database_connection_string,
 	}[matrix_bot_maubot_database_engine]
    }}"


# Defines the port number where the management interface is
# To actually expose the management interface outside of the container, use `matrix_bot_maubot_management_interface_http_bind_port`
matrix_bot_maubot_management_interface_port: 29316

# Controls whether the maubot container exposes its HTTP management interface port (tcp/29316 in the container).
#
# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:29316"), or empty string to not expose.
# If you'll be setting this at all, it should be defined in terms of `matrix_bot_maubot_management_interface_port`.
# Example:
# matrix_bot_maubot_management_interface_http_bind_port: "127.0.0.1:{{ matrix_bot_maubot_management_interface_port }}"
matrix_bot_maubot_management_interface_http_bind_port: ''


matrix_bot_maubot_unshared_secret: 'generate'

# Specifies the default log level for all bot loggers.
matrix_bot_maubot_logging_level: WARNING

# A list of extra arguments to pass to the container
matrix_bot_maubot_container_extra_arguments: []

# List of systemd services that matrix-bot-maubot.service depends on
matrix_bot_maubot_systemd_required_services_list: ['docker.service']

# List of systemd services that matrix-bot-maubot.service wants
matrix_bot_maubot_systemd_wanted_services_list: []
